### PR TITLE
Add PHP version check #17

### PR DESCRIPTION
**Pull request by raftaar1191**
Add PHP version check from both WPCLI and Plugin Menu. It will display a PHP notices on admin area if PHP version is less than 5.3

**Screenshot**
http://prntscr.com/g0oyzg
http://prntscr.com/g0ozdl

### CODE REVIEW

**Comment by ravinderk** [comment]
@raftaar1191 Thank you for PR. I will merge it after testing.

**Comment by ravinderk** [comment]
@raftaar1191 Can we update notice message.
For Ref: https://github.com/Yoast/whip

**Comment by raftaar1191** [comment]
@ravinderk 

I think this message is more than enough to under that we need to upgrade to at least PHP version 5.3.
What else we can do is on the read me file will write about the minimum PHP version needed

**Comment by ravinderk** [comment]
@raftaar1191 alright

**Pull request merged**
